### ISSUE TITLE
Building conda-feedstock fails on Windows during test phase

### ISSUE THREAD

**Issue by aguzmanballen** [AnacondaRecipes/conda-feedstock#2]
Issue:
When running `conda-build conda-feedstock -c defaults --python=3.7`, the build phase is able to complete, but it fails when it runs the following from the feedstock's bld.bat script:
`(base) %SRC_DIR%>CALL conda create -y -p .\built-conda-test-env python=3.5`
<br/>
Error Report:
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\gateways\disk\update.py", line 107, in touch
        mkdir_p_sudo_safe(dirpath)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\gateways\disk\__init__.py", line 84, in mkdir_
p_sudo_safe
        os.mkdir(path)
    FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\aguzmanb\\Development\\Miniconda3.latest\\conda-bld\\conda_15680527453
42\\_test_env\\pkgs'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\subdir_data.py", line 189, in _load
        mtime = getmtime(self.cache_path_json)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\subdir_data.py", line 157, in cache_path_
json
        return self.cache_path_base + '.json'
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\subdir_data.py", line 148, in cache_path_
base
        create_cache_dir(),
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\subdir_data.py", line 649, in create_cach
e_dir
        cache_dir = join(PackageCacheData.first_writable(context.pkgs_dirs).pkgs_dir, 'cache')
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\package_cache_data.py", line 160, in firs
t_writable
        created = create_package_cache_directory(package_cache.pkgs_dir)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\gateways\disk\create.py", line 435, in create_
package_cache_directory
        touch(join(pkgs_dir, PACKAGE_CACHE_MAGIC_FILE), mkdir=True, sudo_safe=sudo_safe)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\gateways\disk\update.py", line 125, in touch
        raise NotWritableError(path, e.errno, caused_by=e)
    conda.exceptions.NotWritableError: The current user does not have write permissions to a required path.
      path: C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\pkgs\urls.txt


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\cli\main_create.py", line 37, in execute
        install(args, parser, 'create')
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\cli\install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\solve.py", line 116, in solve_for_transac
tion
        should_retry_solve)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\solve.py", line 157, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\solve.py", line 261, in solve_final_state

        ssc = self._collect_all_metadata(ssc)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\solve.py", line 414, in _collect_all_meta
data
        index, r = self._prepare(prepared_specs)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\solve.py", line 999, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\index.py", line 214, in get_reduced_index

        repodata_fn=repodata_fn)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\subdir_data.py", line 95, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\concurrent\futures\_base.py", line 598, in result_iterator
        yield fs.pop().result()
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\concurrent\futures\_base.py", line 435, in result
        return self.__get_result()
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\concurrent\futures\_base.py", line 384, in __get_result
        raise self._exception
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\subdir_data.py", line 88, in <lambda>
        package_ref_or_match_spec))
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\subdir_data.py", line 100, in query
        self.load()
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\subdir_data.py", line 164, in load
        _internal_state = self._load()
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\subdir_data.py", line 192, in _load
        self.cache_path_json)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\subdir_data.py", line 157, in cache_path_
json
        return self.cache_path_base + '.json'
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\subdir_data.py", line 148, in cache_path_
base
        create_cache_dir(),
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\core\subdir_data.py", line 650, in create_cach
e_dir
        mkdir_p_sudo_safe(cache_dir)
      File "C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\lib\site-packages\conda\gateways\disk\__init__.py", line 84, in mkdir_
p_sudo_safe
        os.mkdir(path)
    FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\aguzmanb\\Development\\Miniconda3.latest\\conda-bld\\conda_15680527453
42\\_test_env\\pkgs\\cache'

`$ C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\Scripts\conda-script.py create -y -p .\built-conda-test-env python=3.5`

  environment variables:
                 CIO_TEST=<not set>
    CONDA_ALLOW_SOFTLINKS=false
                CONDA_BAT=C:\Users\aguzmanb\Development\Miniconda3.latest\conda-
                          bld\conda_1568052745342\_test_env\condabin\conda.bat
              CONDA_BUILD=1
        CONDA_BUILD_STATE=TEST
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\aguzmanb\Development\Miniconda3.latest\conda-
                          bld\conda_1568052745342\_test_env\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\aguzmanb\Development\Miniconda3.latest\conda-
                          bld\conda_1568052745342\_test_env\condabin\..\Scripts\conda.exe"
                CONDA_LUA=5
                CONDA_NPY=1.11
               CONDA_PERL=5.26.0
             CONDA_PREFIX=C:\Users\aguzmanb\Development\Miniconda3.latest\conda-
                          bld\conda_1568052745342\_test_env
    CONDA_PROMPT_MODIFIER=(base)
                 CONDA_PY=37
         CONDA_PYTHON_EXE=C:\Users\aguzmanb\Development\Miniconda3.latest\conda-
                          bld\conda_1568052745342\_test_env\python.exe
                  CONDA_R=3.4
               CONDA_ROOT=C:\Users\aguzmanb\Development\Miniconda3.latest
              CONDA_SHLVL=1
                FTP_PROXY=<set>
                 HOMEPATH=\Users\aguzmanb
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
      MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared
                          Libraries\compiler\lib\intel64_win_mic
                 NO_PROXY=<set>
                     PATH=C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_156805
                          2745342\_test_env;C:\Users\aguzmanb\Development\Miniconda3.latest\cond
                          a-bld\conda_1568052745342\_test_env\Library\mingw-w64\bin;C:\Users\agu
                          zmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_tes
                          t_env\Library\usr\bin;C:\Users\aguzmanb\Development\Miniconda3.latest\
                          conda-bld\conda_1568052745342\_test_env\Library\bin;C:\Users\aguzmanb\
                          Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\
                          Scripts;C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\cond
                          a_1568052745342\_test_env\bin;C:\Users\aguzmanb\Development\Miniconda3
                          .latest\conda-bld\conda_1568052745342\_test_env;C:\Users\aguzmanb\Deve
                          lopment\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\Libr
                          ary\mingw-w64\bin;C:\Users\aguzmanb\Development\Miniconda3.latest\cond
                          a-bld\conda_1568052745342\_test_env\Library\usr\bin;C:\Users\aguzmanb\
                          Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\
                          Library\bin;C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\
                          conda_1568052745342\_test_env\Scripts;C:\Users\aguzmanb\Development\Mi
                          niconda3.latest\conda-bld\conda_1568052745342\_test_env\bin;C:\Users\a
                          guzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_t
                          est_env\condabin;C:\Users\aguzmanb\Development\Miniconda3.latest\conda
                          -bld\conda_1568052745342\_test_env;C:\Users\aguzmanb\Development\Minic
                          onda3.latest\conda-bld\conda_1568052745342\_test_env;C:\Users\aguzmanb
                          \Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env
                          \Library\mingw-w64\bin;C:\Users\aguzmanb\Development\Miniconda3.latest
                          \conda-bld\conda_1568052745342\_test_env\Library\usr\bin;.;C:\Users\ag
                          uzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_te
                          st_env\Library\bin;C:\Users\aguzmanb\Development\Miniconda3.latest\con
                          da-bld\conda_1568052745342\_test_env\Scripts;C:\Users\aguzmanb\Develop
                          ment\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\Scripts
                          ;C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_15680
                          52745342\_test_env;C:\Users\aguzmanb\Development\Miniconda3.latest\con
                          da-bld\conda_1568052745342\_test_env\Library\mingw-w64\bin;C:\Users\ag
                          uzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_te
                          st_env\Library\usr\bin;.;C:\Users\aguzmanb\Development\Miniconda3.late
                          st\conda-bld\conda_1568052745342\_test_env\Library\bin;C:\Users\aguzma
                          nb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_e
                          nv\Scripts;C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\c
                          onda_1568052745342\_test_env\Scripts;C:\Users\aguzmanb\Development\Min
                          iconda3.latest;C:\Users\aguzmanb\Development\Miniconda3.latest\Library
                          \mingw-w64\bin;C:\Users\aguzmanb\Development\Miniconda3.latest\Library
                          \usr\bin;C:\Users\aguzmanb\Development\Miniconda3.latest\Library\bin;C
                          :\Users\aguzmanb\Development\Miniconda3.latest\Scripts;C:\Users\aguzma
                          nb\Development\Miniconda3.latest\bin;C:\Users\aguzmanb\Development\Min
                          iconda3.latest\condabin;c:\Rtools\bin;c:\Rtools\gcc-4.6.3\bin;C:\Progr
                          amData\Oracle\Java\javapath;C:\Perl64\site\bin;C:\Perl64\bin;C:\Progra
                          m Files (x86)\Common Files\Intel\Shared
                          Libraries\redist\ia32_win\compiler;C:\Program Files (x86)\Common
                          Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files
                          (x86)\Common Files\Intel\Shared
                          Libraries\redist\ia32\compiler;C:\Program Files (x86)\Common
                          Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Windows\sy
                          stem32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Windows
                          PowerShell\v1.0;c:\Program Files (x86)\Microsoft SQL
                          Server\90\Tools\binn;C:\Program Files\Microsoft\Web Platform
                          Installer;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web
                          Pages\v1.0;C:\Program Files\Microsoft SQL
                          Server\110\Tools\Binn;C:\Program Files (x86)\swigwin-3.0.8;C:\Program
                          Files\TortoiseGit\bin;C:\Program Files (x86)\Microsoft
                          SDKs\TypeScript\1.0;C:\Program Files\Microsoft SQL
                          Server\120\Tools\Binn;C:\Program Files\Microsoft SQL
                          Server\130\Tools\Binn;C:\Program Files (x86)\Git\cmd;C:\Program Files
                          (x86)\Git\usr\bin;C:\Program Files (x86)\ProcessExplorer;C:\Program
                          Files (x86)\PuTTY;C:\Program Files\CMake\bin;C:\Program Files
                          (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files
                          (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64;C:\Users\aguzmanb\Deve
                          lopment\Miniconda3;C:\Users\aguzmanb\Development\Miniconda3\Scripts;C:
                          \Users\aguzmanb\Development\Miniconda3\Library\bin;.
             PSMODULEPATH=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
                   PYTHON=C:\Users\aguzmanb\Development\Miniconda3.latest\conda-
                          bld\conda_1568052745342\_test_env\python.exe
           PYTHONHASHSEED=1063183681
         PYTHONNOUSERSITE=1
     PYTHON_MAJOR_VERSION=3
       REQUESTS_CA_BUNDLE=
              RSYNC_PROXY=<set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env
            shell level : 1
       user config file : C:\Users\aguzmanb\.condarc
 populated config files : C:\Users\aguzmanb\.condarc
          conda version : 4.7.11
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages :
       base environment : C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\pkgs
                          C:\Users\aguzmanb\.conda\pkgs
                          C:\Users\aguzmanb\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\envs
                          C:\Users\aguzmanb\.conda\envs
                          C:\Users\aguzmanb\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.4 Windows/2012ServerR2 Windows/6.3.9600
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
```
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at C:\Users\aguzmanb\Development\Miniconda3.latest:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0
beautifulsoup4            4.8.0                    py37_0
bzip2                     1.0.8                he774522_0
ca-certificates           2019.5.15                     1
certifi                   2019.6.16                py37_1
cffi                      1.12.3           py37h7a1dbc1_0
chardet                   3.0.4                    py37_1
conda                     4.7.10                   py37_0
conda-build               3.18.9                   py37_3
conda-package-handling    1.3.11                   py37_0
console_shortcut          0.1.1                         3
cryptography              2.7              py37h7a1dbc1_0
filelock                  3.0.12                     py_0
glob2                     0.7                        py_0
idna                      2.8                      py37_0
jinja2                    2.10.1                   py37_0
libarchive                3.3.3                h0643e63_5
libiconv                  1.15                 h1df5818_7
liblief                   0.9.0                ha925a31_2
libxml2                   2.9.9                h464c3ec_0
lz4-c                     1.8.1.2              h2fa13f4_0
lzo                       2.10                 h6df0209_2
markupsafe                1.1.1            py37he774522_0
menuinst                  1.4.16           py37he774522_0
openssl                   1.1.1c               he774522_1
pip                       19.1.1                   py37_0
pkginfo                   1.5.0.1                  py37_0
powershell_shortcut       0.0.1                         2
psutil                    5.6.3            py37he774522_0
py-lief                   0.9.0            py37ha925a31_2
pycosat                   0.6.3            py37hfa6e2cd_0
pycparser                 2.19                     py37_0
pyopenssl                 19.0.0                   py37_0
pysocks                   1.7.0                    py37_0
python                    3.7.3                h8c8aaf0_1
python-libarchive-c       2.8                     py37_11
pytz                      2019.2                     py_0
pywin32                   223              py37hfa6e2cd_1
pyyaml                    5.1.2            py37he774522_0
requests                  2.22.0                   py37_0
ruamel_yaml               0.15.46          py37hfa6e2cd_0
setuptools                41.0.1                   py37_0
six                       1.12.0                   py37_0
soupsieve                 1.9.2                    py37_0
sqlite                    3.29.0               he774522_0
tqdm                      4.32.1                     py_0
urllib3                   1.24.2                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wheel                     0.33.4                   py37_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : C:\Users\aguzmanb\Development\Miniconda3.latest
    active env location : C:\Users\aguzmanb\Development\Miniconda3.latest
            shell level : 1
       user config file : C:\Users\aguzmanb\.condarc
 populated config files : C:\Users\aguzmanb\.condarc
          conda version : 4.7.11
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages :
       base environment : C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\pkgs
                          C:\Users\aguzmanb\.conda\pkgs
                          C:\Users\aguzmanb\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\aguzmanb\Development\Miniconda3.latest\conda-bld\conda_1568052745342\_test_env\envs
                          C:\Users\aguzmanb\.conda\envs
                          C:\Users\aguzmanb\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.4 Windows/2012ServerR2 Windows/6.3.9600
          administrator : False
             netrc file : None
           offline mode : False

```
</details>

**Comment by msarahan** [comment]
That looks like a race condition.  The index code runs in more than one thread by default.  You can hack that in conda-build with https://github.com/conda/conda-build/blob/master/conda_build/index.py#L109
